### ISSUE TITLE
symmetry.f90 unit test errors

### ISSUE THREAD

**Issue by wsmorgan** [msg-byu/symlib#1]
In the symmetry.xml file there are a number of tests with purpose: `testingf?_dp8vsdp4?`. This is because when fortpy performs the unit test it finds answers to a higher precision, 8, than the 4 that were saved to file for comparison. pysave_real was used to save the output in both cases. Any ideas how to fix this.

**Comment by rosenbrockc** [comment]
If you define a custom XML template for the comparison, you can specify a `<comparisons>` section (see https://github.com/rosenbrockc/fortpy/wiki/File-Comparison-Across-Versions#comparisons-section) that includes a `tolerance` attribute. You can specify the finite precision tolerance with that attribute.

**Comment by wsmorgan** [comment]
Like this?
<?xml version="1.0" encoding="UTF-8"?>
<fortpy mode="template" versions="1">
  <comments versions="1">#</comments>
  <body stop="EOF" versions="1">
    <line id="autovar" type="float" values="*" versions="1" />
  </body>
  <comparison id="autovar" operator="finite"
tolerance="abs($)>abs($+0.000000000001)"/>
</fortpy>

Wiley Morgan
http://hagrid.byu.edu/Wiley#Bio

On Tue, May 26, 2015 at 9:48 AM, Conrad Rosenbrock <notifications@github.com

**Comment by rosenbrockc** [comment]
Almost, take a look at https://github.com/rosenbrockc/fortpy/blob/master/docs/code/mcsimanneal.out.xml

**Comment by wsmorgan** [comment]
Thanks. Got it to work.
