### ISSUE TITLE
Fortpy comparison error?

### ISSUE THREAD

**Issue by wsmorgan** [msg-byu/symlib#3]
ERROR: [autovar] could not parse value '-61.2238249-101.4675892' of type 'float'.
Error produced from cross_product tests in vector_matrix_utilities.f90

**Comment by rosenbrockc** [comment]
It looks like there is a missing space between the two floats. Are you using the standard `float.xml` template?

**Comment by wsmorgan** [comment]
Yes

**Comment by wsmorgan** [comment]
This issue no longer occurs in the cross product, it would appear that the new fortpy.f90 fixed the issue. However, on a similar note in vector_matrix_utilities.f90 the volume test fails half the time with the following error:
`BLOCK: index 0`
`0.00% (0.00% RAW)`
`ITEM   autovar - MISMATCH (616.309005878 vs. 616.309005878)`

The template being used looks like this:
`<?xml version="1.0" encoding="UTF-8"?>`
`<fortpy mode="template" versions="1">`
`<comments versions="1">#</comments>`
`<body stop="EOF" versions="1">`
`<line id="autovar" type="float" values="*" versions="1" />`
`</body>`
`<comparisons version="1" >`
`<compare id="autovar" operator="finite" tolerance="2E-11"/>`
`</comparisons>`
`</fortpy>`

**Comment by rosenbrockc** [comment]
Fortpy was not printing out more than 9 digits in the comparison report; since the values differed in the 11th decimal, the round-off shows them as equivalent. From revision 1.6.0 onwards, we print with `.12f` to make sure they all show up.
